name: CI Workflow

on: [push, pull_request]  # Triggers on push and pull requests

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on a Linux server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Gets your repo code

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Installs Node.js 18

      - name: Install Dependencies
        run: npm install  # Installs project dependencies

      - name: Run Tests
        run: npm test  # Runs your test script
